name: xmake

on:
  push:
    branches: [main]
    paths:
      - ".github/workflows/xmake.yml"
      - "src/**"
      - "tests/**"
      - "xmake.lua"

  pull_request:
    branches: [main]
    paths:
      - ".github/workflows/xmake.yml"
      - "src/**"
      - "tests/**"
      - "xmake.lua"

jobs:
  build:
    strategy:
      matrix:
        os: [windows-2025, ubuntu-latest]

    runs-on: ${{ matrix.os }}

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup GCC 12 (Ubuntu)
        if: matrix.os == 'ubuntu-latest'
        run: |
          sudo apt update
          sudo apt install gcc-12 g++-12

      - name: Show GCC version and STL details
        run: |
          gcc --version
          echo "GCC verbose information:"
          g++ -v

      - name: Setup xmake
        uses: xmake-io/github-action-setup-xmake@v1
        with:
          xmake-version: branch@master
          actions-cache-folder: ".xmake-cache"
          actions-cache-key: ${{ matrix.os }}
          package-cache: true
          package-cache-key: ${{ matrix.os }}

      - name: Clean xmake cache
        run: |
          rm -rf .xmake-cache

      - name: Build (Release)
        run: |
          xmake f --cppstd=c++23 --clean --yes --mode=release
          xmake --verbose --diagnosis

      - name: Build (Debug)
        run: |
          xmake f --cppstd=c++23 --clean --yes --mode=debug
          xmake --verbose --diagnosis
